/*
  Usage:
  mongosh "mongodb://127.0.0.1:27017" --file scripts/seed-feature-data.mongosh.js

  This script resets and seeds:
  - 15 users (1 admin)
  - 25 cases
  - 10 updatecases
  - 10 reports
*/

const DB_NAME = "police_info";
const dbRef = db.getSiblingDB(DB_NAME);

const caseIds = [
  ObjectId("65f100000000000000000001"),
  ObjectId("65f100000000000000000002"),
  ObjectId("65f100000000000000000003"),
  ObjectId("65f100000000000000000004"),
  ObjectId("65f100000000000000000005"),
  ObjectId("65f100000000000000000006"),
  ObjectId("65f100000000000000000007"),
  ObjectId("65f100000000000000000008"),
  ObjectId("65f100000000000000000009"),
  ObjectId("65f10000000000000000000a"),
  ObjectId("65f10000000000000000000b"),
  ObjectId("65f10000000000000000000c"),
  ObjectId("65f10000000000000000000d"),
  ObjectId("65f10000000000000000000e"),
  ObjectId("65f10000000000000000000f"),
  ObjectId("65f100000000000000000010"),
  ObjectId("65f100000000000000000011"),
  ObjectId("65f100000000000000000012"),
  ObjectId("65f100000000000000000013"),
  ObjectId("65f100000000000000000014"),
  ObjectId("65f100000000000000000015"),
  ObjectId("65f100000000000000000016"),
  ObjectId("65f100000000000000000017"),
  ObjectId("65f100000000000000000018"),
  ObjectId("65f100000000000000000019"),
];

const users = [
  {
    fullname: "ADMIN CHIEF",
    police_id: "AC900001",
    contact: "9000000001",
    email: "admin.chief@police.gov.in",
    city: "Gandhinagar",
    password: "admin123",
    isAdmin: true,
    isApproved: true,
  },
  {
    fullname: "ANJALI SINGH",
    police_id: "AS886644",
    contact: "9090900009",
    email: "anjali.singh@police.gov.in",
    city: "Kutch",
    password: "police123",
    isAdmin: false,
    isApproved: true,
  },
  {
    fullname: "DEVAM KARANJIA",
    police_id: "DK334455",
    contact: "9898900001",
    email: "devam.karanjia@police.gov.in",
    city: "Ahmedabad",
    password: "police123",
    isAdmin: false,
    isApproved: true,
  },
  {
    fullname: "HARDIK VAGHELA",
    police_id: "HV779911",
    contact: "9494900005",
    email: "hardik.vaghela@police.gov.in",
    city: "Gandhinagar",
    password: "police123",
    isAdmin: false,
    isApproved: true,
  },
  {
    fullname: "JIGAR RAWAL",
    police_id: "JR002244",
    contact: "9393900006",
    email: "jigar.rawal@police.gov.in",
    city: "Bhavnagar",
    password: "police123",
    isAdmin: false,
    isApproved: true,
  },
  {
    fullname: "MONIKA PATEL",
    police_id: "MP110033",
    contact: "9292900007",
    email: "monika.patel@police.gov.in",
    city: "Anand",
    password: "police123",
    isAdmin: false,
    isApproved: true,
  },
  {
    fullname: "POOJA SOLANKI",
    police_id: "PS224466",
    contact: "9595900004",
    email: "pooja.solanki@police.gov.in",
    city: "Jamnagar",
    password: "police123",
    isAdmin: false,
    isApproved: true,
  },
  {
    fullname: "PRIT CHOTALIYA",
    police_id: "PC556677",
    contact: "9797800003",
    email: "prit.chotaliya@police.gov.in",
    city: "Surendranagar",
    password: "police123",
    isAdmin: false,
    isApproved: true,
  },
  {
    fullname: "RUPESH MODI",
    police_id: "RM557799",
    contact: "9191900008",
    email: "rupesh.modi@police.gov.in",
    city: "Mehsana",
    password: "police123",
    isAdmin: false,
    isApproved: true,
  },
  {
    fullname: "SACHIN DESAI",
    police_id: "SD113355",
    contact: "9696900003",
    email: "sachin.desai@police.gov.in",
    city: "Rajkot",
    password: "police123",
    isAdmin: false,
    isApproved: true,
  },
  {
    fullname: "VIVEK DHAKATE",
    police_id: "VD667788",
    contact: "9797900002",
    email: "vivek.dhakate@police.gov.in",
    city: "Vadodara",
    password: "police123",
    isAdmin: false,
    isApproved: true,
  },
  {
    fullname: "RAHUL NAIK",
    police_id: "RN445566",
    contact: "9111100001",
    email: "rahul.naik@police.gov.in",
    city: "Surat",
    password: "police123",
    isAdmin: false,
    isApproved: false,
  },
  {
    fullname: "KIRAN PANDYA",
    police_id: "KP778899",
    contact: "9222200002",
    email: "kiran.pandya@police.gov.in",
    city: "Junagadh",
    password: "police123",
    isAdmin: false,
    isApproved: false,
  },
  {
    fullname: "NIDHI THAKOR",
    police_id: "NT112233",
    contact: "9333300003",
    email: "nidhi.thakor@police.gov.in",
    city: "Patan",
    password: "police123",
    isAdmin: false,
    isApproved: false,
  },
  {
    fullname: "AMIT MISTRY",
    police_id: "AM990011",
    contact: "9444400004",
    email: "amit.mistry@police.gov.in",
    city: "Morbi",
    password: "police123",
    isAdmin: false,
    isApproved: false,
  },
];

const cases = [
  {
    _id: caseIds[0],
    case_title: "Riverside Park Midnight Homicide",
    case_type: "Homicide (Murder)",
    case_description:
      "A fatal stabbing was reported near Riverside Park after midnight. CCTV and phone records were collected to trace the main suspect network.",
    suspects: [
      { name: "Rohan Patel", age: 32 },
      { name: "Mahesh Rana", age: 29 },
    ],
    victim: [{ name: "Deepak Joshi", age: 34 }],
    guilty_name: [{ name: "Rohan Patel", age: 32 }],
    case_date: new Date("2026-02-18T00:00:00.000Z"),
    case_handler: "SACHIN DESAI",
    status: "ACTIVE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[1],
    case_title: "Industrial Boiler Fatal Negligence Case",
    case_type: "Manslaughter",
    case_description:
      "A worker died after a boiler blast at an industrial unit. Site safety logs and supervisor statements indicate criminal negligence.",
    suspects: [{ name: "Nilesh Parmar", age: 45 }],
    victim: [{ name: "Yogesh Shah", age: 38 }],
    guilty_name: [],
    case_date: new Date("2026-02-05T00:00:00.000Z"),
    case_handler: "DEVAM KARANJIA",
    status: "CLOSE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[2],
    case_title: "Hostel Assault Complaint Sector Nine",
    case_type: "Rape / Sexual Assault",
    case_description:
      "A late night assault complaint was registered from a private hostel. Digital evidence and medical reports were secured.",
    suspects: [{ name: "Karan Mehta", age: 27 }],
    victim: [{ name: "Priya Trivedi", age: 22 }],
    guilty_name: [{ name: "Karan Mehta", age: 27 }],
    case_date: new Date("2026-01-22T00:00:00.000Z"),
    case_handler: "ANJALI SINGH",
    status: "ACTIVE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[3],
    case_title: "School Van Abduction Attempt",
    case_type: "Kidnapping / Abduction",
    case_description:
      "Two men attempted to abduct a child from a school van route. Public camera footage and witness sketches are under verification.",
    suspects: [
      { name: "Harsh Vora", age: 31 },
      { name: "Dipen Gohil", age: 28 },
    ],
    victim: [{ name: "Milan Shah", age: 11 }],
    guilty_name: [],
    case_date: new Date("2025-12-30T00:00:00.000Z"),
    case_handler: "POOJA SOLANKI",
    status: "ACTIVE",
    isApproved: false,
    is_removed: false,
  },
  {
    _id: caseIds[4],
    case_title: "Market Lane Metal Rod Attack",
    case_type: "Aggravated Assault",
    case_description:
      "A targeted assault with a metal rod injured a shop owner during closing hours. Prior threats suggest planned retaliation.",
    suspects: [{ name: "Jatin Solanki", age: 30 }],
    victim: [{ name: "Prakash Dave", age: 41 }],
    guilty_name: [{ name: "Jatin Solanki", age: 30 }],
    case_date: new Date("2025-11-17T00:00:00.000Z"),
    case_handler: "HARDIK VAGHELA",
    status: "ACTIVE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[5],
    case_title: "Bus Stand Argument Turned Violent",
    case_type: "Simple Assault / Battery",
    case_description:
      "A verbal dispute at central bus stand escalated into physical assault. Parties later gave conflicting statements.",
    suspects: [{ name: "Alpesh Mori", age: 26 }],
    victim: [{ name: "Ritesh Barot", age: 25 }],
    guilty_name: [],
    case_date: new Date("2025-10-09T00:00:00.000Z"),
    case_handler: "JIGAR RAWAL",
    status: "CLOSE",
    isApproved: true,
    is_removed: true,
  },
  {
    _id: caseIds[6],
    case_title: "Night Robbery at Highway Fuel Station",
    case_type: "Robbery",
    case_description:
      "Armed robbers looted cash from a highway fuel station at closing time. Vehicle movement and toll data are being matched.",
    suspects: [
      { name: "Suresh Kadam", age: 35 },
      { name: "Firoz Sheikh", age: 33 },
    ],
    victim: [{ name: "Imran Pathan", age: 40 }],
    guilty_name: [{ name: "Suresh Kadam", age: 35 }],
    case_date: new Date("2025-09-14T00:00:00.000Z"),
    case_handler: "MONIKA PATEL",
    status: "ACTIVE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[7],
    case_title: "Green Avenue Bungalow Break In",
    case_type: "Burglary / House Breaking",
    case_description:
      "A bungalow was broken into during a family wedding event. Jewellery and documents were stolen from locked cabinets.",
    suspects: [{ name: "Bhavesh Zala", age: 29 }],
    victim: [{ name: "Neha Trivedi", age: 36 }],
    guilty_name: [],
    case_date: new Date("2025-08-03T00:00:00.000Z"),
    case_handler: "RUPESH MODI",
    status: "CLOSE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[8],
    case_title: "Textile Warehouse Inventory Theft",
    case_type: "Theft (Larceny)",
    case_description:
      "High value fabric rolls were found missing during monthly audit. Internal movement logs indicate organized pilferage.",
    suspects: [{ name: "Ravi Bhoi", age: 24 }],
    victim: [{ name: "Mehul Soni", age: 44 }],
    guilty_name: [],
    case_date: new Date("2025-07-25T00:00:00.000Z"),
    case_handler: "VIVEK DHAKATE",
    status: "ACTIVE",
    isApproved: false,
    is_removed: false,
  },
  {
    _id: caseIds[9],
    case_title: "Luxury SUV Theft Ring Operation",
    case_type: "Motor Vehicle Theft",
    case_description:
      "Multiple SUV theft complaints with cloned key usage were linked to one group. Chassis numbers and scrap trails are under review.",
    suspects: [
      { name: "Chirag Jhala", age: 31 },
      { name: "Sanjay Koli", age: 28 },
    ],
    victim: [{ name: "Nirav Patel", age: 39 }],
    guilty_name: [],
    case_date: new Date("2025-06-11T00:00:00.000Z"),
    case_handler: "PRIT CHOTALIYA",
    status: "ACTIVE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[10],
    case_title: "Municipal Office Glass Damage Incident",
    case_type: "Vandalism / Criminal Damage",
    case_description:
      "Public office windows and records were damaged during a protest spillover. Identity mapping is underway from video evidence.",
    suspects: [{ name: "Viral Chauhan", age: 27 }],
    victim: [],
    guilty_name: [],
    case_date: new Date("2025-05-02T00:00:00.000Z"),
    case_handler: "SACHIN DESAI",
    status: "CLOSE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[11],
    case_title: "Builder Blackmail Through Anonymous Calls",
    case_type: "Extortion / Blackmail",
    case_description:
      "A developer reported repeated extortion calls demanding monthly payments. Call routing suggests spoofed internet telephony.",
    suspects: [{ name: "Raj Malhotra", age: 37 }],
    victim: [{ name: "Anuj Bhandari", age: 46 }],
    guilty_name: [],
    case_date: new Date("2025-04-18T00:00:00.000Z"),
    case_handler: "DEVAM KARANJIA",
    status: "ACTIVE",
    isApproved: false,
    is_removed: true,
  },
  {
    _id: caseIds[12],
    case_title: "E Commerce Admin Panel Breach",
    case_type: "Cybercrime / Hacking",
    case_description:
      "An online store backend was compromised and discount abuse caused major losses. Server logs indicate credential stuffing attacks.",
    suspects: [{ name: "Parth Modi", age: 23 }],
    victim: [{ name: "Rina Shah", age: 33 }],
    guilty_name: [],
    case_date: new Date("2025-03-29T00:00:00.000Z"),
    case_handler: "ANJALI SINGH",
    status: "ACTIVE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[13],
    case_title: "Online Investment App Ponzi Complaint",
    case_type: "Fraud / Cheating",
    case_description:
      "Citizens reported blocked withdrawals from a fake investment app promising daily returns. Wallet addresses were traced.",
    suspects: [{ name: "Ketan Pandey", age: 34 }],
    victim: [
      { name: "Jagdish Rana", age: 52 },
      { name: "Hina Patel", age: 31 },
    ],
    guilty_name: [],
    case_date: new Date("2025-02-14T00:00:00.000Z"),
    case_handler: "HARDIK VAGHELA",
    status: "ACTIVE",
    isApproved: false,
    is_removed: false,
  },
  {
    _id: caseIds[14],
    case_title: "Counterfeit Currency Distribution Cell",
    case_type: "Forgery / Counterfeiting",
    case_description:
      "Fake high denomination notes were circulated through weekly markets. Chemical ink tests confirmed sophisticated counterfeits.",
    suspects: [{ name: "Imtiyaz Khan", age: 36 }],
    victim: [{ name: "Dinesh Modi", age: 48 }],
    guilty_name: [{ name: "Imtiyaz Khan", age: 36 }],
    case_date: new Date("2025-01-08T00:00:00.000Z"),
    case_handler: "JIGAR RAWAL",
    status: "CLOSE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[15],
    case_title: "Cooperative Ledger Embezzlement Probe",
    case_type: "Embezzlement / Breach of Trust",
    case_description:
      "Account reconciliation exposed repeated siphoning from a cooperative credit account over six months.",
    suspects: [{ name: "Kalpesh Raval", age: 42 }],
    victim: [{ name: "Mahendra Patel", age: 55 }],
    guilty_name: [],
    case_date: new Date("2024-12-21T00:00:00.000Z"),
    case_handler: "MONIKA PATEL",
    status: "ACTIVE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[16],
    case_title: "Shell Trading Laundering Trail",
    case_type: "Money Laundering",
    case_description:
      "Funds moved through multiple shell entities and circular invoices. Banking pattern indicates layered laundering activity.",
    suspects: [{ name: "Lokesh Arora", age: 39 }],
    victim: [],
    guilty_name: [],
    case_date: new Date("2024-11-10T00:00:00.000Z"),
    case_handler: "RUPESH MODI",
    status: "CLOSE",
    isApproved: false,
    is_removed: true,
  },
  {
    _id: caseIds[17],
    case_title: "Interstate Synthetic Drug Supply Route",
    case_type: "Drug Offense (NDPS)",
    case_description:
      "Controlled delivery operation revealed interstate synthetic drug transport using parcel vehicles.",
    suspects: [
      { name: "Ramesh Purohit", age: 33 },
      { name: "Akash Nayak", age: 26 },
    ],
    victim: [],
    guilty_name: [],
    case_date: new Date("2024-10-04T00:00:00.000Z"),
    case_handler: "POOJA SOLANKI",
    status: "ACTIVE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[18],
    case_title: "Coastal Contraband Electronics Seizure",
    case_type: "Smuggling / Contraband",
    case_description:
      "Unbilled imported electronics were seized near a coastal warehouse. Shipping manifests were falsified.",
    suspects: [{ name: "Faizan Memon", age: 37 }],
    victim: [],
    guilty_name: [{ name: "Faizan Memon", age: 37 }],
    case_date: new Date("2024-09-19T00:00:00.000Z"),
    case_handler: "VIVEK DHAKATE",
    status: "CLOSE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[19],
    case_title: "Workshop Illegal Weapon Fabrication",
    case_type: "Illegal Weapons",
    case_description:
      "A hidden workshop manufactured improvised firearms and sold them through local middlemen.",
    suspects: [{ name: "Naresh Thakur", age: 41 }],
    victim: [],
    guilty_name: [],
    case_date: new Date("2024-08-07T00:00:00.000Z"),
    case_handler: "PRIT CHOTALIYA",
    status: "ACTIVE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[20],
    case_title: "Basement Betting Network Exposure",
    case_type: "Illegal Gambling",
    case_description:
      "A basement betting operation handled live match gambling via encrypted chat rooms.",
    suspects: [{ name: "Yusuf Qureshi", age: 38 }],
    victim: [],
    guilty_name: [{ name: "Yusuf Qureshi", age: 38 }],
    case_date: new Date("2024-07-01T00:00:00.000Z"),
    case_handler: "SACHIN DESAI",
    status: "CLOSE",
    isApproved: true,
    is_removed: true,
  },
  {
    _id: caseIds[21],
    case_title: "Festival Night Street Rioting",
    case_type: "Public Order / Rioting",
    case_description:
      "A local procession dispute escalated into stone pelting and vehicle damage across two streets.",
    suspects: [
      { name: "Hemant Jadav", age: 29 },
      { name: "Rinku Solanki", age: 24 },
    ],
    victim: [{ name: "Vikas Parmar", age: 31 }],
    guilty_name: [],
    case_date: new Date("2024-06-15T00:00:00.000Z"),
    case_handler: "DEVAM KARANJIA",
    status: "ACTIVE",
    isApproved: false,
    is_removed: false,
  },
  {
    _id: caseIds[22],
    case_title: "Repeated Domestic Abuse Complaint",
    case_type: "Domestic Violence",
    case_description:
      "Victim filed repeated domestic abuse complaints with medical documentation and neighbor statements.",
    suspects: [{ name: "Ankit Chavda", age: 34 }],
    victim: [{ name: "Nisha Chavda", age: 30 }],
    guilty_name: [],
    case_date: new Date("2024-05-09T00:00:00.000Z"),
    case_handler: "ANJALI SINGH",
    status: "ACTIVE",
    isApproved: false,
    is_removed: false,
  },
  {
    _id: caseIds[23],
    case_title: "Minor Missing From Railway Platform",
    case_type: "Missing Person Report",
    case_description:
      "A minor went missing from a crowded railway platform. CCTV frames were circulated to interstate units.",
    suspects: [],
    victim: [{ name: "Rohan Verma", age: 13 }],
    guilty_name: [],
    case_date: new Date("2024-04-26T00:00:00.000Z"),
    case_handler: "HARDIK VAGHELA",
    status: "ACTIVE",
    isApproved: true,
    is_removed: false,
  },
  {
    _id: caseIds[24],
    case_title: "Chain Collision on Ring Road Flyover",
    case_type: "Traffic Accident (Non-Fatal)",
    case_description:
      "A multi vehicle collision caused severe injuries but no fatalities. Overspeed and lane changes are under analysis.",
    suspects: [{ name: "Harit Shah", age: 27 }],
    victim: [
      { name: "Bharat Patel", age: 46 },
      { name: "Leena Shah", age: 35 },
    ],
    guilty_name: [],
    case_date: new Date("2024-03-13T00:00:00.000Z"),
    case_handler: "MONIKA PATEL",
    status: "CLOSE",
    isApproved: true,
    is_removed: false,
  },
];

const updatecases = [
  {
    originalCaseId: caseIds[0],
    case_title: "Riverside Park Homicide Supplementary",
    case_type: "Homicide (Murder)",
    case_description:
      "New witness statement and forensic timeline were added. One additional suspect was linked through call detail records.",
    suspects: [
      { name: "Rohan Patel", age: 32 },
      { name: "Mahesh Rana", age: 29 },
      { name: "Amit Solanki", age: 30 },
    ],
    victim: [{ name: "Deepak Joshi", age: 34 }],
    guilty_name: [{ name: "Rohan Patel", age: 32 }],
    case_date: new Date("2026-02-19T00:00:00.000Z"),
    case_handler: "SACHIN DESAI",
    status: "ACTIVE",
    requestedAt: new Date("2026-02-20T08:30:00.000Z"),
  },
  {
    originalCaseId: caseIds[1],
    case_title: "Industrial Boiler Negligence Reclassification",
    case_type: "Manslaughter",
    case_description:
      "Expert inspection report shows bypassed safety valve and forged maintenance entries.",
    suspects: [
      { name: "Nilesh Parmar", age: 45 },
      { name: "Rakesh Suthar", age: 40 },
    ],
    victim: [{ name: "Yogesh Shah", age: 38 }],
    guilty_name: [{ name: "Nilesh Parmar", age: 45 }],
    case_date: new Date("2026-02-06T00:00:00.000Z"),
    case_handler: "DEVAM KARANJIA",
    status: "ACTIVE",
    requestedAt: new Date("2026-02-19T11:00:00.000Z"),
  },
  {
    originalCaseId: caseIds[2],
    case_title: "Hostel Assault Complaint Sector Nine Revised",
    case_type: "Rape / Sexual Assault",
    case_description:
      "Victim statement updated and additional digital chat evidence attached for prosecution review.",
    suspects: [{ name: "Karan Mehta", age: 27 }],
    victim: [{ name: "Priya Trivedi", age: 22 }],
    guilty_name: [{ name: "Karan Mehta", age: 27 }],
    case_date: new Date("2026-01-23T00:00:00.000Z"),
    case_handler: "ANJALI SINGH",
    status: "CLOSE",
    requestedAt: new Date("2026-02-18T15:45:00.000Z"),
  },
  {
    originalCaseId: caseIds[4],
    case_title: "Market Lane Assault Weapon Recovery",
    case_type: "Aggravated Assault",
    case_description:
      "Recovered weapon matched blood trace findings. Charge sections were expanded after medical board review.",
    suspects: [{ name: "Jatin Solanki", age: 30 }],
    victim: [{ name: "Prakash Dave", age: 41 }],
    guilty_name: [{ name: "Jatin Solanki", age: 30 }],
    case_date: new Date("2025-11-18T00:00:00.000Z"),
    case_handler: "HARDIK VAGHELA",
    status: "CLOSE",
    requestedAt: new Date("2026-02-17T09:10:00.000Z"),
  },
  {
    originalCaseId: caseIds[6],
    case_title: "Highway Fuel Station Robbery Updated",
    case_type: "Robbery",
    case_description:
      "Second getaway vehicle was identified and one accused linked to prior armed robberies.",
    suspects: [
      { name: "Suresh Kadam", age: 35 },
      { name: "Firoz Sheikh", age: 33 },
      { name: "Niraj Khatri", age: 31 },
    ],
    victim: [{ name: "Imran Pathan", age: 40 }],
    guilty_name: [{ name: "Suresh Kadam", age: 35 }],
    case_date: new Date("2025-09-16T00:00:00.000Z"),
    case_handler: "MONIKA PATEL",
    status: "ACTIVE",
    requestedAt: new Date("2026-02-16T10:30:00.000Z"),
  },
  {
    originalCaseId: caseIds[7],
    case_title: "Green Avenue Burglary Recovery Note",
    case_type: "Burglary / House Breaking",
    case_description:
      "Partial property recovery completed after raid on resale channel. Complainant inventory verified.",
    suspects: [{ name: "Bhavesh Zala", age: 29 }],
    victim: [{ name: "Neha Trivedi", age: 36 }],
    guilty_name: [],
    case_date: new Date("2025-08-05T00:00:00.000Z"),
    case_handler: "RUPESH MODI",
    status: "ACTIVE",
    requestedAt: new Date("2026-02-15T17:20:00.000Z"),
  },
  {
    originalCaseId: caseIds[9],
    case_title: "Luxury SUV Theft Ring Charge Update",
    case_type: "Motor Vehicle Theft",
    case_description:
      "Engine numbers recovered from chop shop matched three complaints, strengthening organized theft charges.",
    suspects: [
      { name: "Chirag Jhala", age: 31 },
      { name: "Sanjay Koli", age: 28 },
    ],
    victim: [{ name: "Nirav Patel", age: 39 }],
    guilty_name: [{ name: "Chirag Jhala", age: 31 }],
    case_date: new Date("2025-06-12T00:00:00.000Z"),
    case_handler: "PRIT CHOTALIYA",
    status: "CLOSE",
    requestedAt: new Date("2026-02-14T12:15:00.000Z"),
  },
  {
    originalCaseId: caseIds[10],
    case_title: "Municipal Office Damage Incident Follow Up",
    case_type: "Vandalism / Criminal Damage",
    case_description:
      "Additional accused were identified from crowd analysis and damage valuation was revised.",
    suspects: [
      { name: "Viral Chauhan", age: 27 },
      { name: "Dhruv Parmar", age: 24 },
    ],
    victim: [],
    guilty_name: [],
    case_date: new Date("2025-05-03T00:00:00.000Z"),
    case_handler: "SACHIN DESAI",
    status: "ACTIVE",
    requestedAt: new Date("2026-02-13T16:50:00.000Z"),
  },
  {
    originalCaseId: caseIds[12],
    case_title: "E Commerce Breach Financial Impact Update",
    case_type: "Cybercrime / Hacking",
    case_description:
      "Fraudulent order trail and IP correlation expanded the suspect map across two states.",
    suspects: [
      { name: "Parth Modi", age: 23 },
      { name: "Sahil Jain", age: 25 },
    ],
    victim: [{ name: "Rina Shah", age: 33 }],
    guilty_name: [],
    case_date: new Date("2025-03-30T00:00:00.000Z"),
    case_handler: "ANJALI SINGH",
    status: "ACTIVE",
    requestedAt: new Date("2026-02-12T08:05:00.000Z"),
  },
  {
    originalCaseId: caseIds[15],
    case_title: "Cooperative Embezzlement Closure Draft",
    case_type: "Embezzlement / Breach of Trust",
    case_description:
      "Audit closure report and repayment ledger were submitted, and recommendation moved toward charge sheet filing.",
    suspects: [{ name: "Kalpesh Raval", age: 42 }],
    victim: [{ name: "Mahendra Patel", age: 55 }],
    guilty_name: [{ name: "Kalpesh Raval", age: 42 }],
    case_date: new Date("2024-12-22T00:00:00.000Z"),
    case_handler: "MONIKA PATEL",
    status: "CLOSE",
    requestedAt: new Date("2026-02-11T13:40:00.000Z"),
  },
];

const reports = [
  {
    email: "citizen.one@mail.com",
    reportText:
      "Streetlights near Old Market remain off after repeated complaints, and theft incidents have increased in that lane at night.",
    date: new Date("2026-02-19T20:10:00.000Z"),
  },
  {
    email: "anjali.singh@police.gov.in",
    reportText:
      "Patrol van GPS failed during a response call, and manual route logging had to be used for the entire late shift.",
    date: new Date("2026-02-17T09:00:00.000Z"),
  },
  {
    email: "resident.kutch@mail.com",
    reportText:
      "Repeated bike racing on the ring road after midnight is causing noise and near-miss accidents for local residents.",
    date: new Date("2026-02-14T23:30:00.000Z"),
  },
  {
    email: "pooja.solanki@police.gov.in",
    reportText:
      "Two CCTV cameras at the station entrance are not recording continuously and need urgent maintenance support.",
    date: new Date("2026-02-10T11:25:00.000Z"),
  },
  {
    email: "shop.owner@mail.com",
    reportText:
      "A suspicious group has been surveying shops before closing time for several days and one attempted break in was noticed.",
    date: new Date("2026-02-05T19:42:00.000Z"),
  },
  {
    email: "sachin.desai@police.gov.in",
    reportText:
      "Case evidence room shelves are near full capacity, and additional sealed storage units are required this month.",
    date: new Date("2026-01-31T08:50:00.000Z"),
  },
  {
    email: "citizen.alert@mail.com",
    reportText:
      "Unknown callers are posing as cyber police and collecting OTP data from senior citizens in our neighborhood.",
    date: new Date("2026-01-21T14:33:00.000Z"),
  },
  {
    email: "vivek.dhakate@police.gov.in",
    reportText:
      "Traffic barricades used at weekend checkpoints are damaged and cannot be safely deployed for high speed corridors.",
    date: new Date("2025-12-15T17:10:00.000Z"),
  },
  {
    email: "housing.society@mail.com",
    reportText:
      "Unauthorized parking and illegal betting activity around the community hall has increased on match nights.",
    date: new Date("2025-11-22T21:18:00.000Z"),
  },
  {
    email: "monika.patel@police.gov.in",
    reportText:
      "Witness follow up calls are delayed because one duty phone line is down, affecting timely statement confirmations.",
    date: new Date("2025-11-10T10:05:00.000Z"),
  },
];

print("Resetting collections in DB:", DB_NAME);
dbRef.users.deleteMany({});
dbRef.cases.deleteMany({});
dbRef.updatecases.deleteMany({});
dbRef.reports.deleteMany({});

const usersRes = dbRef.users.insertMany(users);
const casesRes = dbRef.cases.insertMany(cases);
const updatesRes = dbRef.updatecases.insertMany(updatecases);
const reportsRes = dbRef.reports.insertMany(reports);

print("Seed completed.");
printjson({
  usersInserted: Object.keys(usersRes.insertedIds).length,
  casesInserted: Object.keys(casesRes.insertedIds).length,
  updateCasesInserted: Object.keys(updatesRes.insertedIds).length,
  reportsInserted: Object.keys(reportsRes.insertedIds).length,
});
